### ISSUE TITLE
Pihole-FTL.db empty and not showing any data grafana top ads by domain panel.

### ISSUE THREAD

**Issue by shetubd** [Brandawg93/Pi-Hole-Monitoring#39]
Hello
I get this error at influx sql container and grafana dashboard not showing any data from top block domain. I get other data into panel. 
`raceback (most recent call last):
  File "//main.py", line 129, in <module>
    add_new_results(last)
  File "//main.py", line 78, in add_new_results
    cur.execute(query)
sqlite3.DatabaseError: database disk image is malformed
filling data...
Traceback (most recent call last):
  File "//main.py", line 129, in <module>
    add_new_results(last)
  File "//main.py", line 78, in add_new_results
    cur.execute(query)
sqlite3.DatabaseError: database disk image is malformed`

**Comment by shetubd** [comment]
I delete pihole-FTL.db and restart pihole docker. Then all data show up. I did not understand what is the cause?
